### ISSUE TITLE
Adding the a1111 "Eta noise seed delta" ENSD

### ISSUE THREAD

**Issue by Nightreaver** [shiimizu/ComfyUI_smZNodes#22]
I am not sure it can be easily calculated, but I'm trying to replicate my a1111 images, and it currently doesnt work well.
I just wonder it might also be connected to the ENSD.

Do you mind adding a node for seed generation that includes the a1111 ENSD?

Cheers

**Comment by isben** [comment]
This number cannot be calculated since this is an arbitrary number that was added to the seed in some early (old) Stable-Diffusion UI.
Actually, it doesn't play any role in A1111. You can experiment in A1111 by changing the standard value of 31337 by any other number and compare the generated images. You'll see they are identical.
You can also read this [reddit post](https://www.reddit.com/r/StableDiffusion/comments/10cshp3/what_is_ensd_31337/)

**Comment by shiimizu** [comment]
I've added ENSD (https://github.com/shiimizu/ComfyUI_smZNodes/commit/a038afa41e05bd6f9e347f3d55d991025aea98ac, https://github.com/shiimizu/ComfyUI_smZNodes/commit/b35d79d34e1ce0795931c77a468606ac0f340e2e), but A1111 and ComfyUI outputs differ from each other on ancestral samplers for some reason.

**Comment by shiimizu** [comment]
I've finished implementing ENSD in https://github.com/shiimizu/ComfyUI_smZNodes/commit/417d5447c0072867b1986cf7b4c597d56edae6c7. You can find it in the `Settings` node. I hope that helps.

**Comment by Nightreaver** [comment]
Thanks a lot, I will check if it works :)
