### ISSUE TITLE
Is "RNG" removed from new version?

### ISSUE THREAD

**Issue by ultimatech-cn** [shiimizu/ComfyUI_smZNodes#52]
I just updated to latest version, but found the there are less setting in node "smz_Setting".
Is it removed? Or I didn't use it correctly?

**Comment by shiimizu** [comment]
The [Settings](https://github.com/shiimizu/ComfyUI_smZNodes#settings) node became dynamic, so the inputs you give matter.
As seen in this image:

<img width="1262" alt="Settings-node-showcase" src="https://github.com/shiimizu/ComfyUI_smZNodes/assets/54494639/37b50faa-81f4-41b1-88ec-2b28e9c5708e">

**Comment by shiimizu** [comment]
The [Settings](https://github.com/shiimizu/ComfyUI_smZNodes#settings) node became dynamic, so the inputs you give matter.
As seen in this image:

<img width="1262" alt="Settings-node-showcase" src="https://github.com/shiimizu/ComfyUI_smZNodes/assets/54494639/37b50faa-81f4-41b1-88ec-2b28e9c5708e">

<br>
<br>

Make sure to recreate the node since there are new settings like `eta`, `s_churn`, etc.
